# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app
        image: jsantacruzpy/app-demo:1
        ports:
        - containerPort: 80
