# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
    imagePullSecrets:
      - name: harbor-pull-secret    
    containers:
      - name: app
        image: harbor.lab.local/cicd/app-demo:20
        ports:
        - containerPort: 80
